---
- name: (Container) Install Gitlab Runner
  import_tasks: install-container.yml
  when: gitlab_runner_container_install

- name: (Container) Delete no longer existing runners
  docker_container:
    name: "{{ gitlab_runner_container_name }}-check"
    image: "{{ gitlab_runner_container_image }}:{{ gitlab_runner_container_tag }}"
    command: verify --delete
    mounts: "{{ gitlab_runner_container_mounts }}"
    cleanup: yes
    interactive: yes
    tty: yes
    detach: no
    network_mode: "{{ gitlab_runner_container_network }}"
  register: verified_runners
  changed_when: '"Updated " in verified_runners.container.Output'
  check_mode: no

- name: (Container) List configured runners
  docker_container:
    name: "{{ gitlab_runner_container_name }}-list"
    image: "{{ gitlab_runner_container_image }}:{{ gitlab_runner_container_tag }}"
    command: list
    mounts: "{{ gitlab_runner_container_mounts }}"
    cleanup: yes
    interactive: yes
    tty: yes
    detach: no
    network_mode: "{{ gitlab_runner_container_network }}"
  register: configured_runners
  changed_when: False
  check_mode: no

- name: (Container) Register GitLab Runner
  include_tasks: register-runner-container.yml
  when: gitlab_runner.token is defined or gitlab_runner_registration_token | string | length > 0  # Ensure value is set
  loop: "{{ gitlab_runner_runners }}"
  loop_control:
    index_var: gitlab_runner_index
    loop_var: gitlab_runner

- name: (Container) Set global options
  import_tasks: global-setup.yml

- name: (Container) Configure GitLab Runner
  import_tasks: config-runners-container.yml

- name: (Container) Start the container
  docker_container:
    name: "{{ gitlab_runner_container_name }}"
    image: "{{ gitlab_runner_container_image }}:{{ gitlab_runner_container_tag }}"
    restart_policy: "{{ gitlab_runner_container_restart_policy }}"
    mounts: "{{ gitlab_runner_container_mounts + gitlab_runner_container_mounts_extra}}"
    network_mode: "{{ gitlab_runner_container_network }}"
    restart: true
